### ISSUE TITLE
crash with update gregicality 0.22.3.1 and gregtech 1.15.0.721

### ISSUE THREAD

**Issue by blakpsykozz27** [bruberu/GregTechFoodOption#3]
java.lang.NoClassDefFoundError: gregicadditions/recipes/GACraftingComponents
	at com.bruberu.gregtechfoodoption.recipe.GTFOMachineRecipes.init(GTFOMachineRecipes.java:23)
	at com.bruberu.gregtechfoodoption.recipe.GTFORecipeAddition.init(GTFORecipeAddition.java:12)
	at com.bruberu.gregtechfoodoption.CommonProxy.registerRecipes(CommonProxy.java:93)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_136_CommonProxy_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: gregicadditions.recipes.GACraftingComponents
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.bruberu.gregtechfoodoption.recipe.GTFOMachineRecipes.init(GTFOMachineRecipes.java:23)
	at com.bruberu.gregtechfoodoption.recipe.GTFORecipeAddition.init(GTFORecipeAddition.java:12)
	at com.bruberu.gregtechfoodoption.CommonProxy.registerRecipes(CommonProxy.java:93)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_136_CommonProxy_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4877760656 bytes (4651 MB) / 8174698496 bytes (7796 MB) up to 10856955904 bytes (10354 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx11648m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version       | Source                                             | Signature                                |
	|:----- |:------------------ |:------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft          | 1.12.2        | minecraft.jar                                      | None                                     |
	| LCH   | mcp                | 9.42          | minecraft.jar                                      | None                                     |
	| LCH   | FML                | 8.0.99.99     | forge-1.12.2-14.23.5.2847-universal.jar            | None                                     |
	| LCH   | forge              | 14.23.5.2847  | forge-1.12.2-14.23.5.2847-universal.jar            | None                                     |
	| LCH   | biometweakercore   | 1.0.39        | minecraft.jar                                      | None                                     |
	| LCH   | actuallyadditions  | 1.12.2-r150   | ActuallyAdditions-1.12.2-r150.jar                  | None                                     |
	| LCH   | redstoneflux       | 2.1.1         | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCH   | cofhcore           | 4.6.6         | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCH   | craftstudioapi     | 1.0.0         | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCH   | animania           | 2.0.3.28      | animania-1.12.2-base-2.0.3.28.jar                  | None                                     |
	| LCH   | architecturecraft  | @VERSION@     | architecturecraft-1.12-3.98.jar                    | None                                     |
	| LCH   | crafttweaker       | 4.1.20        | CraftTweaker2-1.12-4.1.20.625.jar                  | None                                     |
	| LCH   | mtlib              | 3.0.6         | MTLib-3.0.6.jar                                    | None                                     |
	| LCH   | modtweaker         | 4.0.18        | modtweaker-4.0.18.jar                              | None                                     |
	| LCH   | jei                | 4.16.1.302    | jei_1.12.2-4.16.1.302.jar                          | None                                     |
	| LCH   | athenaeum          | 1.12.2-1.19.2 | athenaeum-1.12.2-1.19.2.jar                        | None                                     |
	| LCH   | base               | 3.13.0        | base-1.12.2-3.13.0.jar                             | None                                     |
	| LCH   | baubles            | 1.5.2         | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | biometweaker       | 3.2.369       | BiomeTweaker-1.12.2-3.2.369.jar                    | 631f326344f7f5fd7df7eb940760ebd52b7c9c17 |
	| LCH   | codechickenlib     | 3.2.3.358     | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | cofhworld          | 1.4.0         | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCH   | contenttweaker     | 1.12.2-4.9.1  | ContentTweaker-1.12.2-4.9.1.jar                    | None                                     |
	| LCH   | ctgui              | 1.0.0         | CraftTweaker2-1.12-4.1.20.625.jar                  | None                                     |
	| LCH   | crafttweakerjei    | 2.0.3         | CraftTweaker2-1.12-4.1.20.625.jar                  | None                                     |
	| LCH   | dropt              | 1.12.2-1.16.1 | dropt-1.12.2-1.16.1.jar                            | None                                     |
	| LCH   | ic2                | 2.8.221-ex112 | industrialcraft-2-2.8.221-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | forestry           | 5.8.2.422     | forestry_1.12.2-5.8.2.422.jar                      | None                                     |
	| LCH   | ftblib             | 5.4.7.2       | FTBLib-5.4.7.2.jar                                 | None                                     |
	| LCH   | gregtech           | 1.15.0.721    | gregtech-1.12.2-1.15.0.721.jar                     | None                                     |
	| LCH   | gtadditions        | 0.22.3        | Gregicality-1.12.2-0.22.3.1.jar                    | None                                     |
	| LCH   | gcm                | 1.0           | gcm-1.1.2.jar                                      | None                                     |
	| LCH   | gendustry          | 0.0.1         | gendustry-0.0.1.jar                                | None                                     |
	| LCH   | gendustryjei       | 1.0.2         | gendustryjei-1.0.2.jar                             | None                                     |
	| LCH   | gregtechfoodoption | @1.12@        | GregTech+Food+Option-1.12.2-0.6.0.jar              | None                                     |
	| LCH   | gregtech_solarios  | 1.0.0         | Gregtech-Solarios-0.12.52.jar                      | None                                     |
	| LCH   | gtceinventory      | 0.0.2         | gtce-inventory-0.0.2.jar                           | None                                     |
	| LCH   | bcfe               | 1.0           | gtcefe-1.1-1.8.5.436.jar                           | None                                     |
	| LCH   | gtcefe             | 1.1-1.8.5.436 | gtcefe-1.1-1.8.5.436.jar                           | None                                     |
	| LCH   | waila              | 1.8.26        | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCH   | incontrol          | 3.9.18        | incontrol-1.12-3.9.18.jar                          | None                                     |
	| LCH   | journeymap         | 1.12.2-5.7.1  | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCH   | jeid               | 1.0.3-48      | JustEnoughIDs-1.0.3-48.jar                         | None                                     |
	| LCH   | loottweaker        | 0.0.10        | LootTweaker-1.12.2-0.0.10.jar                      | None                                     |
	| LCH   | mantle             | 1.12-1.3.3.55 | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCH   | mcjtylib_ng        | 3.5.4         | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| LCH   | modularmachinery   | 1.10.0        | modularmachinery-1.12.2-1.10.0.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | mysticalmechanics  | 0.18          | Mystical+Mechanics-0.18.jar                        | None                                     |
	| LCH   | nuclearcraft       | 2o.5.3        | NuclearCraft-2o.5.3-1.12.2.jar                     | None                                     |
	| LCH   | patchouli          | 1.0-20        | Patchouli-1.0-20.jar                               | None                                     |
	| LCH   | placebo            | 1.6.0         | Placebo-1.12.2-1.6.0.jar                           | None                                     |
	| LCH   | requious           | 1.0           | Requious+Frakto-0.12.jar                           | None                                     |
	| LCH   | resourceloader     | 1.5.3         | ResourceLoader-MC1.12.1-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | rustichromia       | 0.9           | Rustichromia-0.9.jar                               | None                                     |
	| LCH   | skyresources       | 2.3.8         | skyresources-2.3.9.jar                             | None                                     |
	| LCH   | tfc                | 1.7.18.176    | TerraFirmaCraft-MC1.12.2-1.7.18.176.jar            | None                                     |
	| LCH   | thermalfoundation  | 2.6.7         | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCH   | thermalexpansion   | 5.5.7         | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LCH   | thermaldynamics    | 2.5.6         | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| LCH   | wawla              | 2.6.274       | Wawla-1.12.2-2.6.274.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | yabba              | 1.1.2.54      | YABBA-1.1.2.54.jar                                 | None                                     |
	| LCH   | foundry            | 1.7.18        | ZenFoundry-1.7.18.jar                              | None                                     |

	Loaded coremods (and transformers): 
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  org.dimdev.jeid.JEIDTransformer
GCMCoreMod (gcm-1.1.2.jar)
  com.hjae.gcm.core.GCMTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
GTCELoadingPlugin (gregtech-1.12.2-1.15.0.721.jar)
  gregtech.common.asm.GTCETransformer
BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  me.superckl.biometweakercore.BiomeTweakerASMTransformer
GACoreMod (Gregicality-1.12.2-0.22.3.1.jar)
  gregicadditions.coremod.GAClassTransformer
GACoreMod (GregTech+Food+Option-1.12.2-0.6.0.jar)
  gregicadditions.coremod.GAClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.47' Renderer: 'NVIDIA GeForce GTX 1080/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.47, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Comment by bruberu** [comment]
Should be fixed once 0.6.1 is finished with processing.
