### ISSUE TITLE
1.9.3 crashing upon startup by "loader constraint violation"

### ISSUE THREAD

**Issue by Vetpetmon** [bruberu/GregTechFoodOption#52]
Using Mixin Booter v8.3 and Gregtech 2.7.0. Does not happen with GTFO 1.9.2
```
[12:56:33] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in gregtechfoodoption-1.9.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[12:56:33] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /media/vetpetmon/Backup/multiMC/instances/The World's Gone Cubed- Closed Alpha/.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2860-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2860-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2860-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2860-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "org/spongepowered/asm/launch/GlobalProperties$Keys"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_351]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_351]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_351]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_351]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_351]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_351]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_351]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_351]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_351]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_351]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_351]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_351]
	at org.spongepowered.asm.launch.GlobalProperties.get(GlobalProperties.java:124) ~[!mixinbooter-8.3.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.isSubsystemRegistered(MixinBootstrap.java:206) ~[MixinBootstrap.class:?]
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:139) ~[MixinBootstrap.class:?]
	at org.spongepowered.asm.launch.MixinBootstrap.init(MixinBootstrap.java:128) ~[MixinBootstrap.class:?]
	at gregtechfoodoption.GTFOMixinPlugin.initMixin(GTFOMixinPlugin.java:43) ~[gregtechfoodoption-1.9.3.jar:?]
	at gregtechfoodoption.GTFOMixinPlugin.<clinit>(GTFOMixinPlugin.java:13) ~[gregtechfoodoption-1.9.3.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_351]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_351]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2860-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860-universal.jar:?]
	... 8 more
[12:56:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[12:56:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[12:56:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[12:56:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:101)
[12:56:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:985)
[12:56:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:76)
Exception caught from launcher
net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:101)
	at java.lang.System.exit(System.java:985)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exiting with ERROR
```

There's a lot of security functions being set off. Is there sandbox breaking/malicious code in the mod?

**Comment by bruberu** [comment]
I was having difficulty with mixins actually being registered for unknown reasons, and so added MixinBootstrap.init() to my mixin plugin to avoid other crashes. However, I cannot actually replicate this issue, so I'll have to look more into it. Do other people get this error upon playing your pack?

**Comment by Vetpetmon** [comment]
Nope, nobody else is currently playing the in-dev version of my modpack. It may be caused by having old configs.

**Comment by bruberu** [comment]
Potentially; it seems like something may or may not be wrong with system settings as well? I have really no clue. I also use Ubuntu and APT, but I do have 7.0-develop at the moment. I also use java 362 rather java 351, which honestly seems like the most likely culprit.

**Comment by bruberu** [comment]
Apparently using mixinbooter 8.1 might also fix it, according to someone else who once got a similar error.

**Comment by bruberu** [comment]
Could you also upload a debug.log?

**Comment by Vetpetmon** [comment]
[debug.log](https://github.com/bruberu/GregTechFoodOption/files/12034135/debug.log)

Downgrading to mixinbooter 8.1 did not solve the crash, nor did moving the JRE up to 361 work.

**Comment by bruberu** [comment]
The next most likely thing is that GTFO is somehow conflicting with one of your mods. If you're not willing to share a modpack zip file with me for me to test on my own, at least check to see if the same modlist crashes on a different computer. If it does crash, then it's almost certainly some sort of mod conflict that you could try to find by disabling mods and relaunching, but if it doesn't, then it's probably a system issue.

**Comment by AVGsqrt2** [comment]
Seems like I'm getting the same issue, no mods except Gregtech ceu 2.7.1,  gtfo 1.9.3, mixinbooter and codechickenlib are intalled.

**Comment by bruberu** [comment]
https://drive.google.com/file/d/1D569jqYSLUS1Xp0YltfOotO5W_-WZ55m/view?usp=sharing Try using this particular testing version.

**Comment by AVGsqrt2** [comment]
Looks like it fixed the issue, it won't crash anymore
