### ISSUE TITLE
Can't open GUI of machines

### ISSUE THREAD

**Issue by lubinacourec** [bruberu/GregTechFoodOption#55]
I place machine in world and right click it, nothing happens ingame, error in log as follows.
Happens with microwave, slicer, multicooker and cuisine assembler.

Mods:
  [✔] !mixinbooter-8.4
  [✔] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔] gregtech-1.12.2-2.7.3-beta
  [✔] gregtechfoodoption-1.9.4

```
[00:52:06] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: gregtechfoodoption.item.GTFOSimpleMachineMetaTileEntity.getCircuitSlotTooltip(Lgregtech/api/gui/widgets/SlotWidget;)Lgregtech/api/gui/widgets/SlotWidget;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_361]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_361]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_361]
Caused by: java.lang.NoSuchMethodError: gregtechfoodoption.item.GTFOSimpleMachineMetaTileEntity.getCircuitSlotTooltip(Lgregtech/api/gui/widgets/SlotWidget;)Lgregtech/api/gui/widgets/SlotWidget;
	at gregtechfoodoption.item.GTFOSimpleMachineMetaTileEntity.createGuiTemplate(GTFOSimpleMachineMetaTileEntity.java:83) ~[GTFOSimpleMachineMetaTileEntity.class:?]
	at gregtech.api.metatileentity.SimpleMachineMetaTileEntity.createUI(SimpleMachineMetaTileEntity.java:511) ~[SimpleMachineMetaTileEntity.class:?]
	at gregtech.api.metatileentity.MetaTileEntityUIFactory.createUITemplate(MetaTileEntityUIFactory.java:30) ~[MetaTileEntityUIFactory.class:?]
	at gregtech.api.metatileentity.MetaTileEntityUIFactory.createUITemplate(MetaTileEntityUIFactory.java:17) ~[MetaTileEntityUIFactory.class:?]
	at gregtech.api.gui.UIFactory.openUI(UIFactory.java:35) ~[UIFactory.class:?]
	at gregtech.api.metatileentity.MetaTileEntity.onRightClick(MetaTileEntity.java:434) ~[MetaTileEntity.class:?]
	at gregtech.api.block.machines.BlockMachine.func_180639_a(BlockMachine.java:329) ~[BlockMachine.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_361]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_361]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by bruberu** [comment]
For now, downgrade GTCEu to 2.7.2; that should hopefully fix it.

**Comment by bruberu** [comment]
[Release Package.zip](https://github.com/bruberu/GregTechFoodOption/files/12388030/Release.Package.zip)
Try using the mod contained within this zip file, and see if it's properly fixed.
