### ISSUE TITLE
When using the latest version of GregTech CE: Unofficial 1.12.2-1.8.x, the server crashes.

### ISSUE THREAD

**Issue by RanxinStart** [bruberu/GregTechFoodOption#64]
It works fine on the client side, and using GregTech CE: Unofficial version 1.12.2-1.7.x on the server side also works fine. However, using version 1.12.2-1.8.x has caused crashes on the server for 1.8.0, 1.8.1, and 1.8.2.

---------------------reportFile--------------------------
[crash-2023-12-11_20.29.34-server.txt](https://github.com/bruberu/GregTechFoodOption/files/13637118/crash-2023-12-11_20.29.34-server.txt)
----------------------report-----------------------------
WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Aqua Acrobatics Transformer (AquaAcrobatics-1.15.3.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  JechCore (jecharacters-1.12.0-3.7.2.jar)
  ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
  UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  CoreMod (MiniEffects-1.12.2-1.1.0.jar)
  FcCoreMod (ae2fc-1.12.2-1.0.11.jar)
  GTFOEarlyMixinPlugin (gregtechfoodoption-1.10.2.jar)
  WarpDriveCore (WarpDrive-1.12.2-1.5.28.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar)
  ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  MixinBooter (!mixinbooter-8.8.jar)
  GregTechLoadingPlugin (gregtech-1.12.2-2.8.2-beta.jar)
Contact their authors BEFORE contacting forge

(Exception in server tick loop)

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GregTech Food Option (gregtechfoodoption)
Caused by: java.lang.NoClassDefFoundError: gregtech/client/particle/GTParticle
	at gregtechfoodoption.machines.GTFOTileEntities.init(GTFOTileEntities.java:93)
	at gregtechfoodoption.GregTechFoodOption.preInit(GregTechFoodOption.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:632)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:215)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:132)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:644)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:102)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:167)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: gregtech.client.particle.GTParticle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4528f2e8 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:264)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 39 more
Caused by: java.lang.RuntimeException: Attempted to load class gregtech/client/particle/GTParticle for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:60)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	... 41 more

No Mixin Metadata is found in the Stacktrace.

**Comment by RanxinStart** [comment]
Sorry, I just saw that this issue has been resolved.
#63
