### ISSUE TITLE
duplicate id

### ISSUE THREAD

**Issue by blakpsykozz27** [bruberu/GregTechFoodOption#7]
hi
there is a problem with the update there is a duplicate id which causes a crash

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibLoader (# LibLoader.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  CoreMod (TickProfiler-1.12-0.0.10.jar)
  BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  GACoreMod (Gregicality-1.12.2-0.22.5.jar)
  GTCELoadingPlugin (gregtech-1.12.2-1.15.1.735.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  AstralCore (astralsorcery-1.12.2-1.10.24.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 6/24/21 11:48 AM
Description: Initializing game

java.lang.IllegalArgumentException: MetaId 101 is already occupied by item component.bacon (requested by item smore.sixteen)
	at gregtech.api.items.metaitem.MetaItem.addItem(MetaItem.java:210)
	at com.bruberu.gregtechfoodoption.item.GTFOMetaItem.registerSubItems(GTFOMetaItem.java:345)
	at gregtech.common.CommonProxy.registerItems(CommonProxy.java:103)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_318_CommonProxy_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gregtech.api.items.metaitem.MetaItem.addItem(MetaItem.java:210)
	at com.bruberu.gregtechfoodoption.item.GTFOMetaItem.registerSubItems(GTFOMetaItem.java:345)
	at gregtech.common.CommonProxy.registerItems(CommonProxy.java:103)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_318_CommonProxy_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by bruberu** [comment]
Fixed in 0.10.1
